#!/bin/bash

echo "=== @xenova/transformers 库诊断 ==="
echo ""

echo "📦 库安装状态："
npm list @xenova/transformers

echo ""
echo "🔍 问题分析："
echo "❌ 错误: Cannot convert undefined or null to object"
echo "❌ 位置: Object.keys(<anonymous>:null:null)"
echo "❌ 原因: @xenova/transformers 动态导入返回了 undefined 或 null"

echo ""
echo "🛠️ 已实施的修复："
echo "✅ 增强导入验证: 检查 transformers 是否为有效对象"
echo "✅ 函数检查: 验证 pipeline 是否为有效函数"
echo "✅ 详细错误信息: 提供具体的错误原因和解决方案"
echo "✅ 日志增强: 添加更详细的调试信息"

echo ""
echo "🔧 可能的原因和解决方案："

echo ""
echo "1. 模块解析问题:"
echo "   原因: Next.js 模块解析器无法正确解析 @xenova/transformers"
echo "   解决: 检查 Next.js 配置，确保支持动态导入"
echo "   版本: 当前使用 @xenova/transformers@2.17.2"

echo ""
echo "2. 构建配置问题:"
echo "   原因: Next.js 构建时没有正确处理动态导入"
echo "   解决: 检查 next.config.js 配置"
echo "   建议: 添加 webpack 配置支持"

echo ""
echo "3. 库兼容性问题:"
echo "   原因: @xenova/transformers 版本与 Next.js 不兼容"
echo "   解决: 尝试降级或升级到兼容版本"
echo "   测试版本: 2.17.2 (当前版本)"

echo ""
echo "4. 环境变量问题:"
echo "   原因: 环境变量影响了模块加载"
echo "   解决: 检查 .env.local 配置"
echo "   检查: NODE_ENV=development"

echo ""
echo "🧪 调试步骤："
echo "1. 检查库安装: npm list @xenova/transformers"
echo "2. 验证文件存在: ls -la node_modules/@xenova/transformers"
echo "3. 检查入口文件: cat node_modules/@xenova/transformers/package.json"
echo "4. 测试静态导入: 在浏览器控制台尝试静态导入"
echo "5. 检查构建输出: 查看 .next 目录中的构建结果"

echo ""
echo "📝 测试代码 (在浏览器控制台运行):"
echo "// 测试静态导入"
echo "import('@xenova/transformers').then(module => {"
echo "  console.log('Module:', module);"
echo "  console.log('Pipeline:', module.pipeline);"
echo "}).catch(error => {"
echo "  console.error('Import error:', error);"
echo "});"

echo ""
echo "🔧 next.config.js 配置建议:"
echo "/** @type {import('next').NextConfig} */"
echo "const nextConfig = {"
echo "  experimental: {"
echo "    runtime: 'edge',"
echo "  },"
echo "  webpack: (config, { isServer }) => {"
echo "    if (!isServer) {"
echo "      config.resolve.fallback = {"
echo "        fs: false,"
echo "        path: false,"
echo "      };"
echo "    }"
echo "    return config;"
echo "  },"
echo "};"
echo "export default nextConfig;"

echo ""
echo "💡 立即解决方案："
echo "1. 重启开发服务器: npm run dev"
echo "2. 清除构建缓存: rm -rf .next"
echo "3. 重新安装依赖: npm install"
echo "4. 检查浏览器控制台错误"
echo "5. 尝试在浏览器控制台手动测试导入"

echo ""
echo "🎯 替代方案："
echo "如果动态导入持续失败，可以考虑:"
echo "• 使用静态导入 (在组件顶部直接导入)"
echo "• 使用 CDN 版本的库"
echo "• 使用其他 Whisper 实现"
echo "• 降级到服务器端转录"

echo ""
echo "🚀 下一步："
echo "请先运行以下命令检查库的完整性:"
echo "ls -la node_modules/@xenova/transformers/"
echo "cat node_modules/@xenova/transformers/package.json | grep main"

echo ""
echo "然后告诉我检查结果，我会根据具体情况提供更精确的解决方案。"
